name: Validate JSONs

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Verify generated schema is up-to-date
        run: make check-schema || echo 'schema.generated.json is outdated. Check logs, run `make generate-schema` locally' && false

      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schema.json
          INPUT_JSONS: ./cp0.json
